services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - net_dmz
    depends_on:
      - "webapp"

  webapp:
    build: ./webapp
    networks:
      - net_dmz
      - net_interna
    environment:
      - DB_HOST=db
      - DB_PASSWORD=supersecret
    depends_on:
      backend:
        condition: service_healthy
      db:
        condition: service_started

  backend:
    build: ./backend
    networks:
      - net_interna   # Solo accesible desde la red interna (sin firewall interno que bloquee a webapp)
    environment:
      - DB_HOST=db
      - DB_PASSWORD=supersecret
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 5s
      retries: 5
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    networks:
      - net_interna   # Activo principal a proteger - accesible desde webapp sin control adicional
    environment:
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=empresa_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  net_dmz:
    driver: bridge
  net_interna:
    driver: bridge
